#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','h','i','m','i',
        'x','1','0','0','-','l','i','n','u','x','-','g','c','c',' ','-','I','.',
        ' ','-','I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',
        ' ',' ','-','O',' ','-','D','_','_','L','I','T','E','O','S','_','_','\0'
    };
    #define PLATFORM "platform: linux-x86_64"
    #define DATE "built on: Wed Apr  3 15:09:54 2019"
#endif
