/*
 * Automatically generated C config: don't edit
 */
/*
 * Version Number
 */
#define __UCLIBCXX_MAJOR__ 0
#define __UCLIBCXX_MINOR__ 2
#define __UCLIBCXX_SUBLEVEL__ (null)

/*
 * Compiler
 */
#define __LOSCFG_COMPILER_HUAWEILITEOS__ 1
#undef __LOSCFG_COMPILER_LITEOS__
#undef __LOSCFG_COMPILER_HISIV500__
#undef __LOSCFG_COMPILER_HISIV300__
#undef __LOSCFG_COMPILER_HISIV600__

/*
 * Platform
 */
#undef __LOSCFG_PLATFORM_HI3516A__
#undef __LOSCFG_PLATFORM_HI3518EV200__
#undef __LOSCFG_PLATFORM_HI3519__
#undef __LOSCFG_PLATFORM_HI3519V101__
#undef __LOSCFG_PLATFORM_HI3559__
#undef __LOSCFG_PLATFORM_HI3556__
#undef __LOSCFG_PLATFORM_HI3911__
#undef __LOSCFG_PLATFORM_HIM5V100__
#define __LOSCFG_PLATFORM_HI3516CV300__ 1
#undef __LOSCFG_PLATFORM_HI3731__

/*
 * Kernel
 */
#define __LOSCFG_KERNEL_LITEKERNEL__ 1
#define __LOSCFG_KERNEL_EXTKERNEL__ 1
#define __LOSCFG_KERNEL_CPPSUPPORT__ 1
#undef __LOSCFG_KERNEL_CPP_EXCEPTIONS_SUPPORT__
#define __LOSCFG_KERNEL_CPUP__ 1
#define __LOSCFG_KERNEL_DYNLOAD__ 1
#define __LOSCFG_KERNEL_RUNSTOP__ 1
#define __LOSCFG_KERNEL_SCATTER__ 1

/*
 * Lib
 */
#define __LOSCFG_LIB_LIBC__ 1
#undef __LOSCFG_LIB_LIBCMINI__
#define __LOSCFG_LIB_LIBM__ 1
#define __LOSCFG_LIB_ZLIB__ 1

/*
 * Compat
 */
#define __LOSCFG_COMPAT_POSIX__ 1
#define __LOSCFG_COMPAT_LINUX__ 1

/*
 * FileSystem
 */
#define __LOSCFG_FS_VFS__ 1
#define __LOSCFG_FS_FAT__ 1
#define __LOSCFG_FS_FAT_CACHE__ 1
#define __LOSCFG_FS_FAT_CHINESE__ 1
#define __LOSCFG_FS_RAMFS__ 1
#define __LOSCFG_FS_YAFFS__ 1
#undef __LOSCFG_FS_NFS__
#define __LOSCFG_FS_PROC__ 1
#define __LOSCFG_FS_JFFS__ 1

/*
 * Net
 */
#define __LOSCFG_NET_LWIP_SACK__ 1
#define __LOSCFG_NET_WPA__ 1

/*
 * Debug
 */
#undef __LOSCFG_COMPILE_DEBUG__
#undef __LOSCFG_PLATFORM_ADAPT__
#undef __LOSCFG_THUMB__
#undef __LOSCFG_PLATFORM_DVFS__
#define __LOSCFG_DEBUG_VERSION__ 1
#define __LOSCFG_SHELL__ 1
#define __LOSCFG_SHELL_EXCINFO__ 1
#define __LOSCFG_NET_LWIP_SACK_TFTP__ 1
#define __LOSCFG_NET_TELNET__ 1
#undef __LOSCFG_TOOLS_IPERF__
#undef __LOSCFG_NET_PCAP__
#define __LOSCFG_MEMORY_CHECK__ 1
#define __LOSCFG_BASE_MEM_NODE_INTEGRITY_CHECK__ 1
#define __LOSCFG_BASE_MEM_NODE_SIZE_CHECK__ 1
#define __LOSCFG_DRIVERS_UART__ 1
#undef __LOSCFG_PLATFORM_UART_WITHOUT_VFS__
#define __LOSCFG_PLATFORM_OSAPPINIT__ 1

/*
 * Driver
 */
#define __LOSCFG_DRIVERS__ 1
#define __LOSCFG_DRIVERS_GPIO__ 1
#define __LOSCFG_DRIVERS_HIDMAC__ 1
#define __LOSCFG_DRIVERS_NETDEV__ 1
#define __LOSCFG_DRIVERS_HIETH_SF__ 1
#undef __LOSCFG_DRIVERS_HIGMAC__
#define __LOSCFG_DRIVERS_I2C__ 1
#define __LOSCFG_I2C_ADAPTER_COUNT__ 4
#define __LOSCFG_HOST_TYPE_HIBVT__ 1
#define __LOSCFG_DRIVERS_MEM__ 1
#define __LOSCFG_DRIVERS_MMC__ 1
#define __LOSCFG_DRIVERS_MTD__ 1
#define __LOSCFG_DRIVERS_MTD_NAND__ 1
#undef __LOSCFG_DRIVERS_MTD_NAND_HINFC620__
#undef __LOSCFG_DRIVERS_MTD_NAND_HISNFC100__
#define __LOSCFG_DRIVERS_MTD_NAND_HIFMC100__ 1
#undef __LOSCFG_DRIVERS_MTD_NAND_HIFMC100_PARALLEL__
#define __LOSCFG_DRIVERS_MTD_SPI_NOR__ 1
#undef __LOSCFG_DRIVERS_MTD_SPI_NOR_HISFC350__
#define __LOSCFG_DRIVERS_MTD_SPI_NOR_HIFMC100__ 1
#define __LOSCFG_DRIVERS_RANDOM__ 1
#define __LOSCFG_HW_RANDOM_ENABLE__ 1
#define __LOSCFG_DRIVERS_RTC__ 1
#define __LOSCFG_DRIVERS_SPI__ 1
#define __LOSCFG_DRIVERS_SPI_DMA__ 1
#define __LOSCFG_DRIVERS_USB__ 1
#define __LOSCFG_DRIVERS_USB_HOST_DRIVER__ 1
#define __LOSCFG_DRIVERS_USB_HOST_EHCI__ 1
#define __LOSCFG_DRIVERS_USB_DEVICE_CLASS_DRIVERS__ 1

/*
 * USB Device Class Drivers
 */
#define __LOSCFG_DRIVERS_USB_MASS_STORAGE__ 1
#define __LOSCFG_DRIVERS_USB_4G_MODEM__ 1
#define __LOSCFG_DRIVERS_USB_SERIAL__ 1
#define __LOSCFG_DRIVERS_USB_ETHERNET__ 1
#define __LOSCFG_DRIVERS_USB_WIRELESS__ 1
#define __LOSCFG_DRIVERS_USB_DWC_DRIVER__ 1
#define __LOSCFG_DRIVERS_USB2_DEVICE_CONTROLLER__ 1
#define __LOSCFG_DRIVERS_USB_GADGET__ 1

/*
 * USB Gadget Drivers
 */
#define __LOSCFG_DRIVERS_USB_MASS_STORAGE_GADGET__ 1
#define __LOSCFG_DRIVERS_USB_UVC_GADGET__ 1
#define __LOSCFG_DRIVERS_USB_SERIAL_GADGET__ 1
#define __LOSCFG_DRIVERS_USB_ETHERNET_GADGET__ 1
#define __LOSCFG_DRIVERS_USB_DFU_GADGET__ 1
#define __LOSCFG_DRIVERS_VIDEO__ 1

/*
 * Stack Smashing Protector (SSP) Compiler Feature
 */
#undef __LOSCFG_CC_NO_STACKPROTECTOR__
#define __LOSCFG_CC_STACKPROTECTOR__ 1
#undef __LOSCFG_CC_STACKPROTECTOR_ALL__
